# This workflow will build visualseartree visualization tool with Maven, and cache/restore any dependencies to improve the workflow execution time
# Before building we have to make sure all test pass. Once done we then generate release binding "v-" with current branch name.

name: visualsearchtree CI-CD

on:
  push:
    #     branches:
    #       - '*.*.*'
    tags:
      - '*'

jobs:
  CI:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout GitHub Actions
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          architecture: x64
          cache: maven

      - name: Tests
        run: mvn test

      - name: Build
        run: mvn -B package --file pom.xml
  CD:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: CI

    steps:
      - name: Checkout GitHub Actions
        uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          #tag: v${{ steps.extract_branch.outputs.branch }}
          name: Release v${{ steps.extract_branch.outputs.branch }}
          body: ${{ github.event.head_commit.message }}
          generateReleaseNotes: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}